### ISSUE TITLE
X instead of Tick for Covid pass verification

### ISSUE THREAD

**Issue by Mike-LilRegie** [lilregie/scanning-app#2]
After scanning Covid pass and checking someone in, there should be a tick icon:
![Screen Shot 2022-03-08 at 10 27 36 AM](https://user-images.githubusercontent.com/254926/157123415-28e3795c-b8e5-45b6-a32f-a879e07bdd38.png)

Also, note typo - "Verfied"

**Comment by Fallstop** [comment]
The overview with the Covid Pass Verified is still waiting on backend support, as we need the server to store if the covid pass verified on check in. After that is implemented, we can then update the client-side data model to match.
Relevant Messages [here](https://lilregie.slack.com/archives/C02LWF3572S/p1644109739872939) and [here](https://lilregie.slack.com/archives/C02LWF3572S/p1646365064040859).

Nice catch with the typo btw, will be fixed with rest.
